unique_ids:
  forms:
    Form1: JRDLQCSNVKMSACJX5TYEH5EFEWOXUBCT
    FormWeather: '1696366493371737902296066.5822'
  modules:
    FormWeather.utils: CWB5A3KLVPG7M2A4IUN5UOTJ6KT7F4MT
    FormWeather.utils.report: K4YCP2MCYZNNYTS4HD2FKWTZE2AYF574
  server_modules: {}
  assets:
    military (2).png: '1696321909320325088612169.1254'
    standard-page.html: 5W32GNKDT65WZPHPPGH4Y35GALWIXA4R
    theme.css: 2J2WBK6RAWQCFJU6KBVPIUZ5MYW6K3JH
